development:
  extjs_direct:
    endpoint: /direct 
  js_app:
    endpoint: /packages
    root_path: /vendor/js/src/packages
  ssh:
    host: 192.168.56.101
    username: chris
    password: Pa$$w0rd


production:




test:
  extjs_direct:
    endpoint: /direct
  js_app:
    endpoint: /packages
    root_path: /lib/js_app/src/packages


